### ISSUE TITLE
建议将项目中的 Server酱 链接换成推荐链接

### ISSUE THREAD

**Issue by easychen** [zhilv666/jrxy-sign#1]
您好，我是 Server酱的作者 Easy 。注意到您的项目中对接或提及了 Server酱，非常感谢对我们的支持。

这里有一个小建议。Server酱最近推出了「[推荐返现计划](https://mp.weixin.qq.com/s?__biz=MzIzMDA2MDMyNg==&mid=2648303853&idx=1&sn=8aacf1c2567f0b8e02ade8c02f79fd65&chksm=f09470a4c7e3f9b2092858033bd7ba0d2766d392c7ebeb96359c6e5213e268e771bd39c54b1b#rd)」，您可以在项目中Server酱的官网链接后边加上推荐参数，这样在用户从这里进入Server酱并订阅会员后，您的项目将获得2元/单的佣金。

只需要用微信登录[fx.ft07.com](https://fx.ft07.com/) ，然后开通计划就可以获得您的推荐链接，佣金会实时地转入开通账号的微信零钱中。

希望这个计划能让您的开源项目更好。

---

Hello, I am Easy, the author of ServerChan. I noticed that your project has integrated or mentioned ServerChan, and I am very grateful for that.

I have a small suggestion. ServerChan has recently launched a "[Referral Cashback Program](https://mp.weixin.qq.com/s?__biz=MzIzMDA2MDMyNg==&mid=2648303853&idx=1&sn=8aacf1c2567f0b8e02ade8c02f79fd65&chksm=f09470a4c7e3f9b2092858033bd7ba0d2766d392c7ebeb96359c6e5213e268e771bd39c54b1b#rd)". You can add a referral parameter to the link to ServerChan's official website in your project. This way, when users enter ServerChan through your link and subscribe to a membership, your project will earn a commission of 2 RMB per subscription.

You just need to log in to [fx.ft07.com](https://fx.ft07.com/) with WeChat, activate the program, and you will get your referral link. The commission will be instantly transferred to the WeChat Wallet of the account that activated the program.

Even though the earnings might not be substantial, I hope this program can provide some additional support for your open-source project.

**Comment by 303562915** [comment]
你好 别的学校 直接改cqcs可以吗

**Comment by 303562915** [comment]
你好 别的学校 直接改cqcs可以吗

**Comment by zhilv666** [comment]
> 你好 别的学校 直接改cqcs可以吗

![image](https://github.com/user-attachments/assets/1b2ad6d6-3979-4384-9b30-0e67301cc592)
获取你们学校的schoolCode，然后修改就行，至于具体能不能用我就不知道了，因为我们学校已经没用今日校园了

**Comment by 303562915** [comment]
![image](https://github.com/user-attachments/assets/a935e735-e557-4d68-a687-285cd99a6659)
换了 好哥哥可以指导一下吗

**Comment by 303562915** [comment]
![image](https://github.com/user-attachments/assets/434565b5-dd93-4f5a-8384-4dc43bf27498)
我这个是晚间查寝 和打卡应该是一样的吧
![7c4c68409af9254d82839dfe07192ef](https://github.com/user-attachments/assets/fefd0f87-9ae8-48d3-805a-6c4865f7cb0b)

**Comment by zhilv666** [comment]
> ![image](https://private-user-images.githubusercontent.com/73573019/385319368-434565b5-dd93-4f5a-8384-4dc43bf27498.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjM3MzksIm5iZiI6MTczMTQyMzQzOSwicGF0aCI6Ii83MzU3MzAxOS8zODUzMTkzNjgtNDM0NTY1YjUtZGQ5My00ZjVhLTgzODQtNGRjNDNiZjI3NDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE0NTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZmM5ODU0MDFhNjhlMmQ5ZmEzZTI0ODUzNzM3ZDI0NTQyNDA0ODI4ZmY0ZWExODg1OGYzZDM5ODlmMzk3ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.m_lgNZVLgJ-qxtm0CV6GFRfmRSXP2ZjYy2tLBqmzEhc) 我这个是晚间查寝 和打卡应该是一样的吧 ![7c4c68409af9254d82839dfe07192ef](https://private-user-images.githubusercontent.com/73573019/385321310-fefd0f87-9ae8-48d3-805a-6c4865f7cb0b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjM3MzksIm5iZiI6MTczMTQyMzQzOSwicGF0aCI6Ii83MzU3MzAxOS8zODUzMjEzMTAtZmVmZDBmODctOWFlOC00OGQzLTgwNWEtNmM0ODY1ZjdjYjBiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE0NTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5YTc4ZDMwMmFmMWNmMmRhZjlmNmViODc4NmJjNzY5N2QxZDU5MGQwNDkzNTFlYWUwN2RmNWQyYmNkNmI0ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.o9cd6IYRzIoNJdR0cwluRIQyizKfCgNMN_AcNfLVLdQ)

我这个程序之前也是晚打卡的，这个报错看不出什么，但我感觉应该是服务端没有所有报错，你可以把服务端运行，然后把服务端的url填上在看看

**Comment by 303562915** [comment]
好嘞 服务端 jrxy-server-window.exe 运行日志
![image](https://github.com/user-attachments/assets/2cb25563-b74a-46c1-aa3b-37c0deb7fc77)
http://[0.0.0.0](http://0.0.0.0:10001/):10001/打开
![image](https://github.com/user-attachments/assets/50a6ce22-9a73-4757-81e8-49a7e46dbf4f)
http://[127.0.0.1:10001](http://127.0.0.1:10001/)/打开
![image](https://github.com/user-attachments/assets/199076a3-f13e-4b71-a072-0ced4a7a89bb)
好像是哪里的问题？
![image](https://github.com/user-attachments/assets/0d5774b9-0cf7-4e31-910b-fd9fc25cc36b)

**Comment by zhilv666** [comment]
> 好嘞 服务端 jrxy-server-window.exe 运行日志 ![image](https://private-user-images.githubusercontent.com/73573019/385363058-2cb25563-b74a-46c1-aa3b-37c0deb7fc77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NTgzMzksIm5iZiI6MTczMTQ1ODAzOSwicGF0aCI6Ii83MzU3MzAxOS8zODUzNjMwNTgtMmNiMjU1NjMtYjc0YS00NmMxLWFhM2ItMzdjMGRlYjdmYzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAwMzM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMTZhYjJmNmI1MDg1MjAyMDE0ODBjYTRmNTdhYjNiZGM3MGI0ODhmMTM0ZjcyOWRkZDRkMzkzMjFjZTA4ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cLYvNCoLgXbBWGvhz-AbricrxAbbEwrhGyY-Tty7GtU) http://[0.0.0.0](http://0.0.0.0:10001/):10001/打开 ![image](https://private-user-images.githubusercontent.com/73573019/385363898-50a6ce22-9a73-4757-81e8-49a7e46dbf4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NTgzMzksIm5iZiI6MTczMTQ1ODAzOSwicGF0aCI6Ii83MzU3MzAxOS8zODUzNjM4OTgtNTBhNmNlMjItOWE3My00NzU3LTgxZTgtNDlhN2U0NmRiZjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAwMzM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1OTJhOGE0ZTAzMTZiYTgwMjVhYmE3ZjE3YWM0NDQyMWEyOGI2ZDE1NjgwYTZiZGFmNjI2NDBiMmRmYTdjMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w_GyuGjHuZOEJrTS_q0CPABg7slKsAHh1PK5eKvd13o) http://[127.0.0.1:10001](http://127.0.0.1:10001/)/打开 ![image](https://private-user-images.githubusercontent.com/73573019/385364171-199076a3-f13e-4b71-a072-0ced4a7a89bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NTgzMzksIm5iZiI6MTczMTQ1ODAzOSwicGF0aCI6Ii83MzU3MzAxOS8zODUzNjQxNzEtMTk5MDc2YTMtZjEzZS00YjcxLWEwNzItMGNlZDRhN2E4OWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAwMzM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMzYwZTEyM2JhYjQ2MmI2MzVmMWI4Y2M4OWY2MGY3YWY5YjRkNzkxYjA3MzRmZDc2OGI1YjRkY2M0MzczZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lE6JMx8lgj6QoMPRtBh-vLE4fSFb1TnY7l0_FJt1L8k) 好像是哪里的问题？ ![image](https://private-user-images.githubusercontent.com/73573019/385364960-0d5774b9-0cf7-4e31-910b-fd9fc25cc36b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NTgzMzksIm5iZiI6MTczMTQ1ODAzOSwicGF0aCI6Ii83MzU3MzAxOS8zODUzNjQ5NjAtMGQ1Nzc0YjktMGNmNy00ZTMxLTkxMGItZmQ5ZmMyNWNjMzZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAwMzM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZTJiODdiYWY2ZWY3MGRjNjg5NWQwNjA5ZjUxNjgzNDcyY2I2ZTI0ZWJhNjM4YWZhNmZhNWQ0MmE0OTE0Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.o5t72lhTeFf0QeX6rdmPaHn6CUpZH2SfXFB_UZWdEEA)

这个没问题，这就是启动成功，直接把链接填到选填项里面的server_url里面就行，根据你的启动信息，url为http://127.0.0.1:10001/jrxy

**Comment by 303562915** [comment]
![image](https://github.com/user-attachments/assets/75b4f012-a26e-4195-91aa-f44f89061520)
填过了 还是这样报错 
![image](https://github.com/user-attachments/assets/4ebd9b3f-e459-4fbf-a5fd-22e33ab7c419)

**Comment by 303562915** [comment]
![image](https://github.com/user-attachments/assets/21facca8-337e-400c-be04-2eedbfef47ae)
看了一下response 是哪个参数没填吗

报{"status":400,"msg":"accessToken or appId illegal","page":null,"msgDelIds":null,"msgsNew":null,"timestamp":null}
'NoneType' object is not subscriptable

**Comment by zhilv666** [comment]
> ![image](https://private-user-images.githubusercontent.com/73573019/385577391-21facca8-337e-400c-be04-2eedbfef47ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NzgyNDIsIm5iZiI6MTczMTQ3Nzk0MiwicGF0aCI6Ii83MzU3MzAxOS8zODU1NzczOTEtMjFmYWNjYTgtMzM3ZS00MDBjLWJlMDQtMmVlZGJmZWY0N2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA2MDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZGYyZDk2OGFiNzMzOWYyZTMyNDk4YTBlYzBjNDA4ZTNmZjZmMjZhNTNkYTQ5NWQyNmRiZDgwMmYwNWE4MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u8w301uA_iczoIW-Ll-asZaxeDDTg4c-Zgq-sU1zd04) 看了一下response 是哪个参数没填吗
> 
> 报{"status":400,"msg":"accessToken or appId illegal","page":null,"msgDelIds":null,"msgsNew":null,"timestamp":null} 'NoneType' object is not subscriptable

![image](https://github.com/user-attachments/assets/ff4089b9-cb0e-4ef8-a42e-7306004db085)
这些参数都填好了没问题的话，那可能就是请求的url或者参数它变了，或者有其他的不知道的什么原因，你可以抓手机的包看看请求这些有没有什么问题，如果你们学校签到有验证码的话，我这个是没有解决的。

**Comment by 303562915** [comment]
![image](https://github.com/user-attachments/assets/5b874d70-ad2c-478b-a635-6b94bff9f0d7)
刚全改了 院校代码 能输出
但是有个list index out of range
是能用了吗
晚上试试

![image](https://github.com/user-attachments/assets/8b148b04-6aff-4059-9132-b4af02cf8a4f)

前面这个报错是因为啥？

话有我们这个有定位 不需要经纬度参数吗？我看他们的之前版本需要填这个 您这个版本是能绕开这个参数吗？

**Comment by zhilv666** [comment]
> ![image](https://private-user-images.githubusercontent.com/73573019/385631928-5b874d70-ad2c-478b-a635-6b94bff9f0d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODM1NjUsIm5iZiI6MTczMTQ4MzI2NSwicGF0aCI6Ii83MzU3MzAxOS8zODU2MzE5MjgtNWI4NzRkNzAtYWQyYy00NzhiLWE2MzUtNmI5NGJmZjlmMGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA3MzQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZDNiNjgwNjFiNGE2YzJiMTYyNTBlZjIwNDUyZDc3MWJjYWM0ZDk1MGE2YzcxZjY2NjM0NjdlNzVlMDFiYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Gp4V-9Jd275k5qiBWvZ3EY3C17nmXtnwsdvu1J97zp0) 刚全改了 院校代码 能输出 但是有个list index out of range 是能用了吗 晚上试试
> 
> ![image](https://private-user-images.githubusercontent.com/73573019/385632193-8b148b04-6aff-4059-9132-b4af02cf8a4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODM1NjUsIm5iZiI6MTczMTQ4MzI2NSwicGF0aCI6Ii83MzU3MzAxOS8zODU2MzIxOTMtOGIxNDhiMDQtNmFmZi00MDU5LTkxMzItYjRhZjAyY2Y4YTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA3MzQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ODBiMzM2NzJmMjQ1MjYyMGFhNDNiZTNlYTAyY2Y5YTdiNzk3YTc5NzljMDM0NDMwZmZlNWU4NWJiNjQ3OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NhfxLAoTCR-neKtEJX95YK0VNBIMD_rTeh9Vq7epRK0)
> 
> 前面这个报错是因为啥？
> 
> 话有我们这个有定位 不需要经纬度参数吗？我看他们的之前版本需要填这个 您这个版本是能绕开这个参数吗？

取值没取到吧，3月份写的代码，也不怎么记得清了，经纬度坐标这些我是获取到前一天打卡的经纬度坐标直接拿来用的，你晚上先看看能不能用吧。

**Comment by 303562915** [comment]
![image](https://github.com/user-attachments/assets/e59746ca-2d60-40bd-880f-7a630dc70927)还是不太行
能查到签到任务

**Comment by zhilv666** [comment]
> ![image](https://private-user-images.githubusercontent.com/73573019/385810952-e59746ca-2d60-40bd-880f-7a630dc70927.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTg5MjIsIm5iZiI6MTczMTU1ODYyMiwicGF0aCI6Ii83MzU3MzAxOS8zODU4MTA5NTItZTU5NzQ2Y2EtMmQ2MC00MGJkLTg4MGYtN2E2MzBkYzcwOTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA0MzAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MzljMzBkMWJhZmI5ZWM1ZTZlZTMyODYwZjk3ZDI3MmNlYWM4Y2NhYmUyNTQ4MzI0MjAyYmZiMzcxMWI4N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TpzeCq8OP8-2mTRa3adE-1xIBbTYk7Bjcrc9MbiUUiI)还是不太行 能查到签到任务

你加我qq：2248952280，我远程帮你看看或者把参数发我 ，我这试试
